### ISSUE TITLE
 swap or 2-opt?

### ISSUE THREAD

**Issue by zcaicaros** [yining043/TSP-improve#1]
In the problem_tsp.py file, from line 32 to line 35, I suppose it to perform a 2-opt operation but I find that you use a swap oepration for some reason?

**Comment by yining043** [comment]
Oh, please feel free to change the code to 2-opt. 2-opt should work better than swap.

**Comment by zcajiayin** [comment]
> Oh, please feel free to change the code to 2-opt. 2-opt should work better than swap.

Got it, thanks. neat code btw.
