### ISSUE TITLE
CUDA Device Problem

### ISSUE THREAD

**Issue by Beau-Yang** [yining043/TSP-improve#2]
I encounter some problems making use of the CUDA to run the code while the code runs normally on the CPU. The following are the specific problems and solutions which resolve the issue for me:
1. I ran the code on the GPU directly and got the error:
`TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`
Modify line 28 of `plots.py`:
```python
# Change the following:
ave_grads.append(p.grad.abs().mean())
# To:
ave_grads.append(p.grad.abs().mean().cpu())
```
2. After solving the TypeError, I met the 'scipy.misc' problem mentioned in the `README.md` and solved it successfully by referring to the issue #27.
3. Afterwards, I got the error:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
Modify line 54 of `plots.py`:
```python
# Change the following:
plt.plot(initial_value.mean() - np.cumsum(reward.cpu().mean(0)))
# To:
plt.plot(initial_value.cpu().mean() - np.cumsum(reward.cpu().mean(0)))
```
Hope these can do some help.

PS: By the way, do you implement the VRP version mentioned in the paper?

**Comment by yining043** [comment]
Thank you Beau-Yang. I will correct them in the code. 

Currently, I haven't yet implemented the VRP version for this framework since I am busing with other projects. But I plan to do so soon. I will update the code as soon as possible when I am able to reproduce the results presented in the paper.
