### ISSUE TITLE
Hi i want to ask how to evaluate the tsplib dataset

### ISSUE THREAD

**Issue by nnhhoang** [yining043/TSP-improve#8]
i want to ask how to evaluate the tsplib dataset

**Comment by yining043** [comment]
Hello, thank you for your question.

In general, you can follow these steps for TSPLIB:

1. Prepare the data file (.pkl file), where the x-y coordinates of the instance are normalized to [0,1]
2. Load the prepared data file and set graph_size accordingly.
3. Run the solver and get the results.
4. Scale the final target value to the original range.
