### ISSUE TITLE
About the tsplib

### ISSUE THREAD

**Issue by nnhhoang** [yining043/TSP-improve#9]
Hello, would it be possible to access the code for tsplib?

I'm also wondering how you dealed with data that are not represented with xy-coordinate like brazil58.tsp?

**Comment by yining043** [comment]
Thanks for your question.

For data that are not represented with xy-coordinates, we need to explicitly give the travel distance between each pair of points. Thus, a matrix containing those travel distances would be desirable, which may be a favourable use case for MatNet - ‘Matrix encoding networks for neural combinatorial optimization, NeurIPS’, whose paper and code are publicly available.

**Comment by nnhhoang** [comment]
Thank you very much !
